# Generated by Django 6.1.2 on 2026-10-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(choices=[('DOCTOR', 'Doctor'), ('RECEPTIONIST', 'Receptionist'), ('OTHER', 'Other Staff')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
