# Generated by Django 6.1.2 on 2026-10-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staff_staff_type_alter_staff_designation'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='staff_members', to='services.service'),
        ),
    ]
